// Os nomes das linhas do tooltip do jogo (TooltipLine.Name), os do tModLoader,
// para o ModifyTooltips achar a linha sem texto solto:
// `line.Name === TooltipNames.Damage`. A descrição tem uma linha por índice:
// TooltipNames.Tooltip(0) é 'Tooltip0'. ReforgePrice e CraftingMaterials só
// existem no celular.
const TooltipNames = Object.freeze({
    ItemName: 'ItemName',
    Favorite: 'Favorite',
    FavoriteDesc: 'FavoriteDesc',
    NoTransfer: 'NoTransfer',
    Shared: 'Shared',
    SharedFrom: 'SharedFrom',
    NoSocial: 'NoSocial',
    Damage: 'Damage',
    CritChance: 'CritChance',
    Speed: 'Speed',
    Knockback: 'Knockback',
    FishingPower: 'FishingPower',
    NeedsBait: 'NeedsBait',
    BaitPower: 'BaitPower',
    Equipable: 'Equipable',
    WandConsumes: 'WandConsumes',
    Quest: 'Quest',
    Vanity: 'Vanity',
    Defense: 'Defense',
    PickPower: 'PickPower',
    AxePower: 'AxePower',
    HammerPower: 'HammerPower',
    TileBoost: 'TileBoost',
    HealLife: 'HealLife',
    HealMana: 'HealMana',
    UseMana: 'UseMana',
    Placeable: 'Placeable',
    Ammo: 'Ammo',
    Consumable: 'Consumable',
    Material: 'Material',
    Wireable: 'Wireable',
    Container: 'Container',
    WireTrigger: 'WireTrigger',
    Tooltip: (index) => 'Tooltip' + index,
    WizardHatDuringAnniversary: 'WizardHatDuringAnniversary',
    BurningBlock: 'BurningBlock',
    MechSummonDuringEverything: 'MechSummonDuringEverything',
    MechdusaSummonNotDuringEverything: 'MechdusaSummonNotDuringEverything',
    EtherianManaWarning: 'EtherianManaWarning',
    WellFedExpert: 'WellFedExpert',
    BuffTime: 'BuffTime',
    OneDropLogo: 'OneDropLogo',
    Expert: 'Expert',
    Master: 'Master',
    PrefixDamage: 'PrefixDamage',
    PrefixSpeed: 'PrefixSpeed',
    PrefixCritChance: 'PrefixCritChance',
    PrefixUseMana: 'PrefixUseMana',
    PrefixSize: 'PrefixSize',
    PrefixShootSpeed: 'PrefixShootSpeed',
    PrefixKnockback: 'PrefixKnockback',
    PrefixArmorPenetration: 'PrefixArmorPenetration',
    PrefixTagDamage: 'PrefixTagDamage',
    PrefixAccDefense: 'PrefixAccDefense',
    PrefixAccMaxMana: 'PrefixAccMaxMana',
    PrefixAccCritChance: 'PrefixAccCritChance',
    PrefixAccDamage: 'PrefixAccDamage',
    PrefixAccMoveSpeed: 'PrefixAccMoveSpeed',
    PrefixAccMeleeSpeed: 'PrefixAccMeleeSpeed',
    SetBonus: 'SetBonus',
    LoadoutShareHint: 'LoadoutShareHint',
    JourneyResearch: 'JourneyResearch',
    JourneyResearchByTeammate: 'JourneyResearchByTeammate',
    BestiaryNotes: 'BestiaryNotes',
    CraftingMaterials: 'CraftingMaterials',
    Price: 'Price',
    SpecialPrice: 'SpecialPrice',
    ReforgePrice: 'ReforgePrice',
});
